### ISSUE TITLE
Front-end broken since v3.2.12

### ISSUE THREAD

**Issue by hacknug** [lucagrandicelli/yearly-archive-facetwp#2]
5.0 introduced `wp.hooks` to core and the FacetWP team renamed their library to `FWP.hooks`. I've fixed it on my fork (https://github.com/hacknug/yearly-archive-facetwp/commit/89d766384879f940cfe7a4dac7043f08e4c94481) but maybe it'd be a better idea to check the WordPress and plugin versions to use either one or the other.

More info: https://facetwp.com/facetwp-and-wordpress-5-0-what-you-need-to-know/

Let me know if you'd like me to open a PR with the changes.

**Comment by hacknug** [comment]
We could use `get_option( 'FACETWP_VERSION' )` or `FACETWP_VERSION` to check if the plugin version is 3.2.12 or bigger and `bloginfo( 'version' )` for the WordPress one.

**Comment by lucagrandicelli** [comment]
Closing this issue. Opening another to introduce backward compatibility with older FacetWP versions.
